# vim: filetype=swayconfig   

# kanshi detector de monitores
exec_always sh -c 'pkill kanshi; kanshi -c ~/.config/sway/kanshi/config'
# waybar
exec_always sh -c 'sleep 0.5; pkill waybar; waybar -c ~/.config/sway/waybar/config.jsonc -s ~/.config/sway/waybar/style.css'
exec_always nm-applet
